---

- hosts: all
  become: true
  pre_tasks:

    - name: Update repo cache (Debian, Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install recommended initial packages (Debian, Ubuntu)
      tags: always
      package:
        name:
          - htop
          - vim
          - tmux
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  become: true
  roles:
    - base

- hosts: proxmox
  become: true
  roles:
    - proxmox

- hosts: apt_mirror
  become: true
  roles:
    - apt_mirror
    
