- name: Install packages for repohub
  tags: repository,repo
  package:
    name: "{{ packages_apt_mirror }}"
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: copy nginx config
  tags: repository,repo
  copy:
    src: nginx_repohub
    dest: /etc/nginx/sites-available/repohub
    owner: root
    group: root
    mode: 0644
  notify: restart_nginx

- name: Validate nginx configuration
  tags: repository,repo
  command: nginx -t
  register: nginx_test
  notify: restart_nginx
  changed_when: false
  ignore_errors: yes

- name: Show Nginx test output
  debug:
    msg: "{{ nginx_test.stdout_lines + nginx_test.stderr_lines }}"

- name: Fail if Nginx configuration is invalid
  fail:
    msg: "Nginx configuration test failed! Check for errors."
  when: nginx_test.rc != 0

- name: Check if symlink exists
  stat:
    path: /etc/nginx/sites-enabled/repohub
  register: symlink_status

- name: Create symlink if it doesnt exist
  file:
    src: /etc/nginx/sites-available/repohub
    dest: /etc/nginx/sites-enabled/repohub
    state: link
  when: not symlink_status.stat.exists
  notify: restart_nginx
  register: symlink_creation

- name: Display change status
  debug:
    msg: "Symlink was created"
  when: symlink_creation.changed

- name: start nginx service (Debian, Ubuntu)
  tags: repository,repo
  service:
    name: nginx
    state: started
    enabled: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: copy apt_mirror config
  tags: repository,repo
  copy:
    src: mirror.list
    dest: /etc/apt/mirror.list
    owner: root
    group: root
    mode: 0644
    register: apt-mirror

- name: create timer unit for apt-mirror
  tags: repository,repo
  copy:
    src: apt-mirror.timer
    dest: /etc/systemd/system/apt-mirror.timer
    owner: root
    group: root
    mode: 0644

- name: create service unit for apt-mirror
  tags: repository,repo
  copy:
    src: apt-mirror.service
    dest: /etc/systemd/system/apt-mirror.service
    owner: root
    group: root
    mode: 0644

- name: start apt-mirror timer (Debian, Ubuntu)
  tags: repository,repo
  systemd:
    name: apt-mirror.timer
    enabled: yes
    state: started
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Ensure apt-mirror service is enabled
  service:
    name: apt-mirror.service
    enabled: yes

